### ISSUE TITLE
not found evidence_for_delex.json

### ISSUE THREAD

**Issue by xubuvd** [lizi-git/MMConv#1]
# python generate_inputs.py
Loading image_classes.json...
Loaded image_classes.json to <class 'dict'> object
Loading ../dataset/evidence_for_delex.json...
Traceback (most recent call last):
  File "generate_inputs.py", line 27, in <module>
    data = load(path + 'evidence_for_delex.json')
  File "~/MMConv/MMDST/utils/json_utils.py", line 41, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/evidence_for_delex.json'

**Comment by liziliao** [comment]
Thanks, we have uploaded.
