### ISSUE TITLE
The image data in "data/images"

### ISSUE THREAD

**Issue by YangXiaocui1215** [lizi-git/MMConv#2]
Hi,  This work is of great help to me.

I can't find the image data that these ids are shown in the dialogue.json. 
Can release the corresponding the image dataset ? 

Thanks very much!!! Looking forward to your reply！

**Comment by liziliao** [comment]
Hi, you may download the images via https://drive.google.com/file/d/1gjt41sJYm3afzghUphNIkwQeeOPsxn52/view?usp=sharing. Please let me know if there is any other problem. Thanks.
